### ISSUE TITLE
Unrelated Request

### ISSUE THREAD

**Issue by nobananasforyou** [Asd-g/AviSynth-vsTBilateral#1]
Hello, 

I would like to thank you for your contributions. I wasn't able to find a way to contact you so I created an issue here. Sorry about that. I was wondering if it be possible for you to update yatta as well for avs+? https://github.com/myrsloik/yatta-ivtc

Kind Regards.

**Comment by Asd-g** [comment]
I will check it.

**Comment by nobananasforyou** [comment]
Thank you so much! 

doom9: https://forum.doom9.org/showthread.php?t=64440
binaries: http://ivtc.org/

**Comment by Asd-g** [comment]
It has Pascal that I cannot help with.
Good luck.

**Comment by nobananasforyou** [comment]
Okay. No worries!
