### ISSUE TITLE
vsBilateral

### ISSUE THREAD

**Issue by realfinder** [Asd-g/AviSynth-vsTBilateral#2]
Hi

I discussed with a friend that use vs about deringing, he said that https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Bilateral is good for this and also for halos, and it's work better than TBilateral

so can we have Bilateral port in avs+?

Thanks

**Comment by Asd-g** [comment]
Hi,

I will port it.
I probably need a week.

**Comment by realfinder** [comment]
thanks, take your time

**Comment by Asd-g** [comment]
You can check [it here](https://github.com/Asd-g/AviSynth-Bilateral/releases).

**Comment by realfinder** [comment]
thanks, I will check it now, and as a side note https://github.com/HomeOfVapourSynthEvolution/VapourSynth-Bilateral/pull/9 and https://github.com/Asd-g/AviSynth-Bilateral/blob/5dc6940eb07d0aea8a254e278c2d314cf4de8184/src/Bilateral.cpp#L767

so the "Default: algorithmY = algorithmU = algorithmV = 1."

should be  Default: algorithmY = algorithmU = algorithmV = 0.
